version: "3.9"

services:   
  mongodb:
    image: mongo:7.0
    volumes:
      - ./data/mongodb:/data/db
      - ./dumps/mongodb:/dumps

#    rabbitmq:
#      image: rabbitmq
#      healthcheck:
#        test: [ "CMD", "rabbitmqctl", "status"]
#        interval: 5s
#        timeout: 20s
#        retries: 5
  
#    hpc_dispatcher:
#      volumes:
#        - ./hpc_dispatcher:/app
#      build: hpc_dispatcher
#      stdin_open: true
#      tty: true
#      depends_on:
#        rabbitmq:
#          condition: service_healthy

  bio_api:
    build: .
    volumes:
      - .:/app
      - ./dmx_data:/dmx_data
      - ./test_client/input_data:/input_data
    ports:
      - "8000:8000"
    tty: true
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
        mongodb:
          condition: service_started
    #   rabbitmq:
    #     condition: service_healthy
    #   hpc_dispatcher:
    #     condition: service_started

  test_client:
    build: ./test_client
    volumes:
      - ./test_client:/app
    tty: true
    depends_on:
      bio_api:
        condition: service_started
      # mongodb:
      #   condition: service_started
      # rabbitmq:
      #   condition: service_healthy

